server:
  port: 8081

spring:
  flyway:
    baseline-on-migrate: true

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: wll0913
