server:
  port: 8000

spring:
  flyway:
    baseline-on-migrate: true
#    locations: db/migration,db/migration-mock

jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: root
  password:
#  wll0913